#ifndef NGE3_SDL_WINDOWFLAGS_H
#define NGE3_SDL_WINDOWFLAGS_H

#include <SDL2/SDL.h>

namespace nge::sdl {
enum class WindowFlags {
  FULLSCREEN = SDL_WINDOW_FULLSCREEN,
  FULLSCREEN_DESKTOP = SDL_WINDOW_FULLSCREEN_DESKTOP,
  OPENGL = SDL_WINDOW_OPENGL,
  VULKAN = SDL_WINDOW_VULKAN,
  SHOWN = SDL_WINDOW_SHOWN,
  HIDDEN = SDL_WINDOW_HIDDEN,
  BORDERLESS = SDL_WINDOW_BORDERLESS,
  RESIZABLE = SDL_WINDOW_RESIZABLE,
  MINIMIZED = SDL_WINDOW_MINIMIZED,
  MAXIMIZED = SDL_WINDOW_MAXIMIZED,
  INPUT_GRABBED = SDL_WINDOW_INPUT_GRABBED,
  INPUT_FOCUS = SDL_WINDOW_INPUT_FOCUS,
  MOUSE_FOCUS = SDL_WINDOW_MOUSE_FOCUS,
  FOREIGN = SDL_WINDOW_FOREIGN,
  ALLOW_HIGHDPI = SDL_WINDOW_ALLOW_HIGHDPI,
  MOUSE_CAPTURE = SDL_WINDOW_MOUSE_CAPTURE,
  ALWAYS_ON_TOP = SDL_WINDOW_ALWAYS_ON_TOP,
  SKIP_TASKBAR = SDL_WINDOW_SKIP_TASKBAR,
  UTILITY = SDL_WINDOW_UTILITY,
  TOOLTIP = SDL_WINDOW_TOOLTIP,
  POPUP_MENU = SDL_WINDOW_POPUP_MENU,
  POS_CENTERED = SDL_WINDOWPOS_CENTERED
};
WindowFlags operator|(const WindowFlags &lhs, const WindowFlags &rhs);

// inline const int WINDOW_FULLSCREEN = SDL_WINDOW_FULLSCREEN;
// inline const int WINDOW_FULLSCREEN_DESKTOP = SDL_WINDOW_FULLSCREEN_DESKTOP;
// inline const int WINDOW_OPENGL = SDL_WINDOW_OPENGL;
// inline const int WINDOW_VULKAN = SDL_WINDOW_VULKAN;
// inline const int WINDOW_SHOWN = SDL_WINDOW_SHOWN;
// inline const int WINDOW_HIDDEN = SDL_WINDOW_HIDDEN;
// inline const int WINDOW_BORDERLESS = SDL_WINDOW_BORDERLESS;
// inline const int WINDOW_RESIZABLE = SDL_WINDOW_RESIZABLE;
// inline const int WINDOW_MINIMIZED = SDL_WINDOW_MINIMIZED;
// inline const int WINDOW_MAXIMIZED = SDL_WINDOW_MAXIMIZED;
// inline const int WINDOW_INPUT_GRABBED = SDL_WINDOW_INPUT_GRABBED;
// inline const int WINDOW_INPUT_FOCUS = SDL_WINDOW_INPUT_FOCUS;
// inline const int WINDOW_MOUSE_FOCUS = SDL_WINDOW_MOUSE_FOCUS;
// inline const int WINDOW_FOREIGN = SDL_WINDOW_FOREIGN;
// inline const int WINDOW_ALLOW_HIGHDPI = SDL_WINDOW_ALLOW_HIGHDPI;
// inline const int WINDOW_MOUSE_CAPTURE = SDL_WINDOW_MOUSE_CAPTURE;
// inline const int WINDOW_ALWAYS_ON_TOP = SDL_WINDOW_ALWAYS_ON_TOP;
// inline const int WINDOW_SKIP_TASKBAR = SDL_WINDOW_SKIP_TASKBAR;
// inline const int WINDOW_UTILITY = SDL_WINDOW_UTILITY;
// inline const int WINDOW_TOOLTIP = SDL_WINDOW_TOOLTIP;
// inline const int WINDOW_POPUP_MENU = SDL_WINDOW_POPUP_MENU;

// inline const int WINDOWPOS_CENTERED = SDL_WINDOWPOS_CENTERED;
} // namespace nge::sdl

#endif